version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ratatouille
    volumes:
      - ./sql/NewDb.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/NewQueries.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ratatouille23@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  java:
    image: openjdk:17-jdk-alpine
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    working_dir: /app
    command: java -jar myapp.jar
volumes:
  local_pgdata:
  pgadmin-data: